main/urls.py
from django.urls import path, include

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.story3, name='home'),
    path('story-1', views.story1, name='story1'),
    path('story-3-exp', views.story3creation, name='story3exp'),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('form-matkul/', include('story5app.urls')),
    path('story6/', include('story6.urls')),
]

story5app/urls.py
from django.urls import path, include

from . import views

app_name = 'story5'

urlpatterns = [
    path('', views.formulir, name='form'),
    path('list-matkul', views.daftar, name='list'),
    path('detail-matkul/<id_matkul>', views.detail, name='detail'),
    path('delete/<hapus_id>', views.hapus, name='delete'),
]

story6/urls.py
from django.urls import path
from . import views

app_name = "story6"

urlpatterns = [
    path('', views.index, name='index'),
    path('form-pendaftar/<int:id>', views.add_pendaftar, name='addPendaftar'),
    path('form-kegiatan/', views.add_kegiatan, name='addKegiatan'),
]

main/models.py
from django.db import models

# Create your models here.

story5app/models.py
from django.db import models

class MataKuliah(models.Model):
    nama_Matkul= models.CharField(max_length=100, default=None)
    dosen = models.CharField(max_length=100)
    jumlah_SKS = models.CharField(max_length=10)
    deskripsi = models.CharField(max_length=200)
    semester = models.CharField(max_length=100)
    ruang = models.CharField(max_length=100)

    def __str__(self):
        return "{}.{}".format(self.id, self.nama_Matkul)

story6/models.py
from django.db import models

class Kegiatan(models.Model):
    nama_kegiatan = models.CharField(max_length=100)

    def __str__(self):
        return self.kegiatan

class Pendaftar(models.Model):
    nama_pendaftar = models.CharField(max_length=100)
    kegiatan_pendaftar = models.ForeignKey(Kegiatan, on_delete=models.CASCADE, related_name='pendaftar')

    def __str__(self):
        return self.nama

story5app/forms.py
from django import forms
from .models import MataKuliah

class FormMatkul(forms.ModelForm):
    class Meta:
        model = MataKuliah
        fields = [
            'nama_Matkul', 
            'dosen', 
            'jumlah_SKS', 
            'deskripsi', 
            'semester', 
            'ruang'
        ]

story6/forms.py
from django import forms
from .models import Kegiatan, Pendaftar

class FormKegiatan(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = '__all__'

class FormPendaftar(forms.ModelForm):
    class Meta:
        model = Pendaftar
        fields = '__all__'

main/views.py
from django.shortcuts import render


def story1(request):
    return render(request, 'main/story1/story1.html')

def story3(request):
    return render(request, 'main/story3/index.html')

def story3creation(request):
    return render(request, 'main/story3/creation.html')   

story5app/views.py
from django.shortcuts import render, redirect
from .forms import FormMatkul
from .models import MataKuliah

# Create your views here.

def daftar(request):
    daftar_matkul = MataKuliah.objects.all()
    context = {
        'daftar_matkul': daftar_matkul,
    }

    return render(request, 'story5/list.html', context)

def formulir(request):
    form = FormMatkul(request.POST or None)
    if form.is_valid() and request.method == 'POST':
        form.save()
        return redirect('story5:list')
    
    context = {
        'form': form
        }

    return render(request, 'story5/form.html', context)

def hapus(request, hapus_id):
    MataKuliah.objects.filter(id=hapus_id).delete()
    return redirect('story5:list')

def detail(request, id_matkul):
    nama_matkul = MataKuliah.objects.get(id=id_matkul).nama_Matkul
    dosen = MataKuliah.objects.get(id=id_matkul).dosen
    sks = MataKuliah.objects.get(id=id_matkul).jumlah_SKS
    desc = MataKuliah.objects.get(id=id_matkul).deskripsi
    semester = MataKuliah.objects.get(id=id_matkul).semester
    ruang = MataKuliah.objects.get(id=id_matkul).ruang

    context = {
        'nama_matkul': nama_matkul,
        'dosen': dosen,
        'sks': sks,
        'deskripsi': desc,
        'semester': semester,
        'ruang': ruang
    }

    return render(request, 'story5/detail.html', context)

story6/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .models import Kegiatan, Pendaftar
from .forms import FormKegiatan, FormPendaftar


def index(request):
    form = FormPendaftar(request.POST or None)
    kegiatan = Kegiatan.objects.all()
    context = {
        'daftar_kegiatan' : kegiatan,
        'form_pendaftar' : FormPendaftar,
    }

    return render(request,'story6/index.html', context)

def add_pendaftar(request, id=None):
    form_pendaftar = FormPendaftar(request.POST or None)
    kegiatan_pendaftar = Kegiatan.objects.get(id=id)

    if (form_pendaftar.is_valid() and request.method == 'POST'):
        nama_pendaftar = form_pendaftar["nama_pendaftar"].value()
        pendaftar = Pendaftar(kegiatan_pendaftar=kegiatan_pendaftar, nama_pendaftar=nama_pendaftar)
        pendaftar.save()
    
    return HttpResponseRedirect('/story6/')

def add_kegiatan(request):
    form_kegiatan = FormKegiatan(request.POST or None)
    context = {
        "form_kegiatan" : FormKegiatan,
    }

    if (form_kegiatan.is_valid() and request.method == 'POST'):
        form_kegiatan.save()
        return HttpResponseRedirect('story6:index')

    return render(request, 'story6/form-kegiatan.html', context)

# def index(request):
#     if (request.method == 'POST'):
#         kegiatan = Kegiatan.objects.all()
#         form_pendaftar = FormPendaftar(request.POST or None)
#         nama_pendaftar = form_pendaftar["nama_pendaftar"].value()
#         id_peserta = int(request.POST['id'])
#         kegiatan_pendaftar = Kegiatan.objects.get(id=id_peserta)
#         pendaftar = Pendaftar(kegiatan_pendaftar=kegiatan_pendaftar, nama_pendaftar=nama_pendaftar)
#         pendaftar.save()
#         daftar_peserta = Pendaftar.objects.all()

#         context = {
#             'daftar_kegiatan' : kegiatan,
#             'form_pendaftar' : FormPendaftar,
#             'daftar_peserta' : daftar_peserta,
#         }

#         return render(request, 'story6/index.html', context)

#     else:
#         kegiatan = Kegiatan.objects.all()
#         daftar_peserta = Pendaftar.objects.all()

#         context = {
#             'daftar_kegiatan' : kegiatan,
#             'daftar_peserta' : daftar_peserta,
#         }

#         return render(request, 'story6/index.html', context)

main/templates/main/story1/story1.html
{% extends 'base.html' %}
{% load static %}

{% block tambahan %}
<link rel="stylesheet" href="{% static 'main/css/style1.css' %}">
<title>Lemon's Story 1</title>
{% endblock tambahan %}

{% block content %}
<div class="identitas">
    <img src="{% static 'main/img_story1/me.jpg' %}">
    <table class="table1">
        <tr>
            <td>Nama:</td>
            <td>Lela Monica Fitriany</td>
        </tr>
        <tr>
            <td>NPM:</td>
            <td>1906353896</td>
        </tr>
        <tr>
            <td>Angkatan:</td>
            <td>2019</td>
        </tr>
        <tr>
            <td>Hobi:</td>
            <td><i>Overthinking</i></td>
        </tr>
        <tr>
            <td>Tentang Saya:</td>
            <td>Seorang mahasiswi Universitas Indonesia jurusan Sistem Informasi
                yang memiliki minat di bidang IT dan sedang berusaha mengasah kemampuannya.</td>
        </tr>
    </table>
</div>
<table class="table2">
    <tr>
        <th colspan="2">Riwayat Pendidikan</th>
    </tr>
    <tr>
        <th>Nama Institusi</th>
        <th>Tahun</th>
    </tr>
    <tr>
        <td>Universitas Indonesia
        </td>
        <td>2019 - Sekarang</td>
    </tr>
    <tr>
        <td>SMAN 2 Kota Cirebon</td>
        <td>2016 - 2019</td>
    </tr>
    <tr>
        <td>SMPN 1 Kota Cirebon</td>
        <td>2013 - 2016</td>
    </tr>
    <tr>
        <td>SDI Al-Azhar 3 Kota Cirebon</td>
        <td>2007 - 2013</td>
    </tr>
    <tr>
        <td>TKI Al-Azhar 3 Kota Cirebon</td>
        <td>2005 - 2007</td>
    </tr>
</table>
<div class="social">
    <a class="icon" href="https://twitter.com/jack"><img src="{% static 'main/img_story1/twitter (1).png' %}"></a>
    <a class="icon" href="https://www.facebook.com/lelamonica.fitriany"><img src="{% static 'main/img_story1/facebook.png' %}"></a>
    <a class="icon" href="https://www.instagram.com/lela.mnc/"><img src="{% static 'main/img_story1/instagram.png' %}"></a>
</div>
{% endblock content %}

main/templates/main/story3/creation.html
{% extends 'base.html' %}
{% load static %}

{% block tambahan %}
<link rel="stylesheet" href="{% static 'main/css/style3.css' %}">
<title>Lemon's Experiences</title>
{% endblock tambahan %}

{% block content %}
<div class="jumbotron jumbotron-exp">
  <div class="experiences">
    <h2 class="head-section">Experiences</h2>
    <hr>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img class="d-block w-100" src="{% static 'main/img_story3/sbf.png' %}" alt="First slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="{% static 'main/img_story3/betis.png' %}" alt="Second slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="{% static 'main/img_story3/coming-soon.png' %}" alt="Third slide">
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
</div>
{% endblock content %}

main/templates/main/story3/index.html
{% extends 'base.html' %}
{% load static %}

{% block tambahan %}
<link rel="stylesheet" href="{% static 'main/css/style3.css' %}">
<title>Lemon's Story 3</title>
{% endblock tambahan %}

{% block content %}
<div class="jumbotron jumbotron-profile">
  <div class="profile">
    <h2 class="head-section">Profile</h2>
    <hr>
    <img src="{% static 'main/img_story3/CircleMe.png' %}">
    <h4>Lela Monica Fitriany</h4>
    <p>An Information System student at University of Indonesia who is striving for success</p>
  </div>
</div>

<div class="container-fluid container-details">
  <div class="row mb-1">
    <div class="col text-center">
      <h4>About Me:</h4>
    </div>
  </div>

  <div class="row mx-5 justify-content-center">
    <div class="col-md-4">
      <ul class>
        <li id="emoji">Born in Sukabumi, 28th of December 2000</li>
        <li id="emoji">Currently live in Cirebon, West Java</li>
        <li id="emoji">I like playing games and reading short fictions</li>
      </ul>
    </div>
  </div>
</div>

<div class="container-fluid container-background" id="background">
  <div class="row pb-4">
    <div class="col text-center">
      <h2 class="head-section">Background</h2>
      <hr>
    </div>
  </div>

  <div class="row">

    <div class="col-md">
      <div class="card">
        <img src="{% static 'main/img_story3/Makara_UI.png' %}" class="card-img-top">
        <div class="card-body">
          <p class="card-text"><u>Universitas Indonesia</u><br>2019 - 2023 (Expected)</p>
        </div>
      </div>
    </div>

    <div class="col-md">
      <div class="card">
        <img src="{% static 'main/img_story3/smanda.png' %}" class="card-img-top">
        <div class="card-body">
          <p class="card-text"><u>SMAN 2 Cirebon</u><br>2016 - 2019</p>
        </div>
      </div>
    </div>

    <div class="col-md">
      <div class="card">
        <img src="{% static 'main/img_story3/spensa.png' %}" class="card-img-top">
        <div class="card-body">
          <p class="card-text"><u>SMPN 1 Cirebon</u><br>2013 - 2016</p>
        </div>
      </div>
    </div>

    <div class="col-md">
      <div class="card">
        <img src="{% static 'main/img_story3/CircleAlazhar.png' %}" class="card-img-top">
        <div class="card-body">
          <p class="card-text"><u>SDI Al-Azhar 3 Cirebon</u><br>2007 - 2013</p>
        </div>
      </div>
    </div>

  </div>
</div>

<div class="container-fluid container-contact" id="contact">
  <div class="row">
    <div class="col-md">
      <h2 class="head-section">Contact</h2>
    </div>
  </div>
</div>

<div class="container-fluid container-icon">
  <div class="row">
    <div class="col-md">
      <a class="icon" href="https://twitter.com/day6official"><img src="{% static 'main/img_story3/iconfinder_online_social_media_twitter_734377.png' %}"></a>
      <a class="icon" href="https://www.facebook.com/lelamonica.fitriany"><img src="{% static 'main/img_story3/iconfinder_facebook_online_social_media_734399.png' %}"></a>
      <a class="icon" href="https://www.instagram.com/lela.mnc/"><img src="{% static 'main/img_story3/iconfinder_instagram_online_social_media_734394.png' %}"></a>
    </div>
  </div>
</div>

<footer>
  <p>Created with &#10084; by Lela Monica</p>
</footer>
{% endblock content %}

story5app/templates/story5/detail.html
{% extends 'base.html' %}
{% load static %}

{% block tambahan %}
<link rel="stylesheet" href="{% static 'story5/css/style5.css' %}">
<title>Detail Matkul</title>
{% endblock tambahan %}

{% block content %}
<h1>Detail Mata Kuliah {{ nama_matkul }}</h1>
<ul class="list-group">
    <li class="list-group-item">Nama Mata Kuliah : {{ nama_matkul }}</li>
    <li class="list-group-item">Nama Dosen : {{ dosen }}</li>
    <li class="list-group-item">Jumlah SKS : {{ sks }} </li>
    <li class="list-group-item">Deskripsi : {{ deskripsi }}</li>
    <li class="list-group-item">Semester : {{ semester }}</li>
    <li class="list-group-item">Ruangan : {{ ruang }}</li>
</ul>
<a class="btn btn-primary" href="{% url 'story5:list' %}">Kembali</a>
{% endblock content %}

story5app/templates/story5/form.html
{% extends 'base.html' %}
{% load static %}

{% block tambahan %}
<link rel="stylesheet" href="{% static 'story5/css/style5.css' %}">
<title>Form Matkul</title>
{% endblock tambahan %}

{% block content %}
<h1>Formulir Mata Kuliah</h1>
<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    
    <input class="btn btn-success" type='submit' value='Simpan'>
</form>
{% endblock content %}

story5app/templates/story5/list.html
{% extends 'base.html' %}
{% load static %}

{% block tambahan %}
<link rel="stylesheet" href="{% static 'story5/css/style5.css' %}">
<title>Daftar Matkul</title>
{% endblock tambahan %}

{% block content %}
<h1>Daftar Mata Kuliah</h1>
<table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col">No</th>
        <th scope="col">Nama Matkul</th>
        <th scope="col">Hapus</th>
    </tr>
    </thead>
    <tbody>
        {% for matkul in daftar_matkul %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td><a href="{% url 'story5:detail' matkul.id %}">{{matkul.nama_Matkul}}</td></a>
                <td><a class="btn btn-danger" href="{% url 'story5:delete' matkul.id %}">Hapus</a></td>
            </tr>
        {% endfor %}
    </tbody>
  </table>
  <a class="btn btn-warning" href="{% url 'story5:form' %}">Tambah</a>
{% endblock content %}

story6/templates/story6/form-kegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block tambahan %}
<link rel="stylesheet" href="{% static 'story6/css/style6.css' %}">
<title>Form Kegiatan</title>
{% endblock tambahan %}

{% block content %}
<h1 style="text-align: center;">Formulir Kegiatan</h1>

<div class="row d-flex justify-content-center">
    <form method="POST">
        {% csrf_token %}
        <div class="form-group justify-content-center">
          <label for="exampleInputEmail1">Nama Kegiatan: </label>
          {{ form_kegiatan.nama_kegiatan }}
          <small id="emailHelp" class="form-text text-muted">Isi nama kegiatan yang mau kamu lakuin bareng aku</small>
        </div>
        <div class="row justify-content-center">
            <button type="submit" class="btn btn-primary ">Simpan</button>
        </div>
    </form>
</div>

  
<!-- <form method="POST">
    {% csrf_token %}
    <table>
        {{ form_kegiatan.nama_kegiatan }}
    </table>
    
    <input class="btn btn-success" type='submit' value='Simpan'>
</form> -->
{% endblock content %}

story6/templates/story6/index.html
{% extends 'base.html' %}
{% load static %}

{% block tambahan %}
<link rel="stylesheet" href="{% static 'story6/css/style6.css' %}">
<title>My Schedule</title>
{% endblock tambahan %}

{% block content %}
<h1 style="text-align: center;">My Schedule</h1>

{% if daftar_kegiatan %}

<div class="row">
{% for kegiatan in daftar_kegiatan %}
    <div class="col-md text-center">
        <div class="card" style="width: 18rem; margin: 0 auto; float: none; margin-bottom: 30px;">
            <div class="card-body">
            <h3 class="card-title">{{ kegiatan.nama_kegiatan }}</h3>
            <p class="card-text">Pendaftar: </p>
                {% if kegiatan.pendaftar.all|length > 0 %}
    
                {% for nama in kegiatan.pendaftar.all %}
                <ul>
                    <li>{{ nama }}</li>
                </ul>
                {% endfor %}
    
                {% else %}
                    <p>Belum ada yang join :(</p>
                {% endif %}

                <!-- {% for peserta in daftar_peserta %}

                {% if peserta.kegiatan_pendaftar == kegiatan %}
                <ul>
                    <li>{{ peserta.nama_pendaftar }}</li>
                </ul>
                {% else %}
                    <p>Belum ada yang join :(</p>
                {% endif %}
                {% endfor %} -->
    
                <form action="{% url 'story6:addPendaftar' kegiatan.id %}" method="POST">
                    {% csrf_token %}
                    {{ form_pendaftar.nama_pendaftar }}
            
                    <input class="btn btn-primary" type='submit' value='Join Kuy'>
                </form>
            </div>
        </div>
    </div>
    

    <!-- <div class="card" style="width: 18rem;">
        <div class="card-body">
        <h3 class="card-title">{{ kegiatan.nama_kegiatan }}</h3>
        <p class="card-text">Daftar Pendaftar: </p>
            {% if kegiatan.pendaftar.all|length > 0 %}

            {% for nama in kegiatan.pendaftar.all %}
            <ul>
                <li>{{ nama }}</li>
            </ul>
            {% endfor %}

            {% else %}
                <p>Belum ada yang join :(</p>
            {% endif %}

            <form action="{% url 'story6:addPendaftar' kegiatan.id %}" method="POST">
                {% csrf_token %}
                {{ form_pendaftar.nama_pendaftar }}
        
                <input class="btn btn-primary" type='submit' value='Join Kuy'>
            </form>

        <a href="#" class="card-link">Card link</a>
        </div>
    </div> -->

    <!-- <h3>{{ kegiatan.nama_kegiatan }}</h3>

    <p>Pendaftar: </p>

    {% if kegiatan.pendaftar.all|length > 0 %}

    {% for nama in kegiatan.pendaftar.all %}
        <p>{{ nama }}</p>
    {% endfor %}

    {% else %}
        <p>Belum ada yang join :(</p>
    {% endif %}

    <form action="{% url 'story6:addPendaftar' kegiatan.id %}" method="POST">
        {% csrf_token %}
        {{ form_pendaftar.nama_pendaftar }}

        <input class="btn btn-primary" type='submit' value='Join Kuy'>
    </form> -->


{% endfor %}
</div>

{% endif %}
    
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- CSS only -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- JS, Popper.js, and jQuery -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

  {% block tambahan %}
  {% endblock tambahan %}
</head>

<body>
    <div class="menu-bar">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <img src="{% static 'main/img_story3/lemon (2).png' %}">
        <a class="navbar-brand" href="#">Lela Monica</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-auto">
            <a class="nav-link" href="{% url 'main:home' %}">Story 3</a>
            <a class="nav-link" href="{% url 'main:story3exp' %}">Experiences</a>
            <a class="nav-link" href="{% url 'main:story1' %}">Story 1</a>
            <a class="nav-link" href="{% url 'story5:form' %}">Form Matkul</a>
            <a class="nav-link" href="{% url 'story5:list' %}">Daftar Matkul</a>
            <a class="nav-link" href="{% url 'story6:index' %}">My Schedule</a>
            <a class="nav-link" href="{% url 'story6:addKegiatan' %}">Form Kegiatan</a>
          </div>
        </div>
      </nav>
    </div>

    {% block content %}
    {% endblock content %}
</body>
  
</html>